spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa

  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
      enabled: true

logging:
  level:
    ROOT: ERROR
