spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa

  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
      enabled: true
logging:
  level:
    org.springframework.jdbc.core.namedparam.NamedParameterJdbcOperations: DEBUG
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
