spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/library
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  mvc:
    hiddenmethod:
      filter:
        enabled: true


logging:
  level:
    ROOT: INFO
